version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      #- $(aws ecr get-login-password --region us-west-2)
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 962804699607.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo build Docker image on `date`
      #- cd src
      #- docker build -t atzm-cap2-image:latest .
      #- docker tag atzm-cap2-image:latest 962804699607.dkr.ecr.us-west-2.amazonaws.com/atzm-cap2:latest
      - docker build -t atzm-cap2 .
      - docker tag atzm-cap2:latest 962804699607.dkr.ecr.us-west-2.amazonaws.com/atzm-cap2:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      #- docker push 962804699607.dkr.ecr.us-west-2.amazonaws.com/atzm-cap2:latest
      - docker push 962804699607.dkr.ecr.us-west-2.amazonaws.com/atzm-cap2:latest
      - echo Writing image definitions file...
      - printf '[{"name":"atzm-cap2-container","imageUri":"962804699607.dkr.ecr.us-west-2.amazonaws.com/atzm-cap2:latest"}]' > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
